export const QUERY_KEYS = {
    API_GET_REGIONS: "API_GET_REGIONS",
    API_GET_PRODUCT: "API_GET_PRODUCT",
    API_GET_CATEGORIES: "API_GET_CATEGORIES",
    API_GET_PRODUCTS: "API_GET_PRODUCTS",
    API_GET_COLLECTION: "API_GET_COLLECTION",
    API_GET_COLLECTIONS: "API_GET_COLLECTIONS",
    API_GET_LOCALIZED_COLLECTION: "LOCALIZED_COLLECTION",
    API_GET_LOCALIZED_CATEGORY: "API_GET_LOCALIZED_CATEGORY",
    API_GET_LOCALIZED_PRODUCT: "API_GET_LOCALIZED_PRODUCT",
    API_GET_LOCALIZED_VARIANTS: "API_GET_LOCALIZED_VARIANTS",
};
